version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: dockerpostgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todopostgres
    ports:
      - "5431:5432"
    restart: always

